supabase:
  url: ${SUPABASE_URL}
  anon: ${SUPABASE_ANON_KEY}
  jwt_secret: ${SUPABASE_JWT_SIGNER}
spring:
  redis:
    host: localhost
    port: 6379
  application:
    name: FileHandler
  datasource:
    url: ${SUPABASE_DATABASE_URL}
    driverClassName: org.postgresql.Driver

    # ←—— hikari must be here, indented under spring.datasource
    hikari:
      maximum-pool-size: 1
      minimum-idle: 1
  jpa:
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: validate
        jdbc:
          lob:
            non_contextual_creation: true
server:
  error:
    whitelabel:
      enabled: true
    include-stacktrace: always
  address: localhost
  port: ${PORT:8080}
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %highlight(%-5level) %yellow(%logger{40}.%M\\(%class{0}.java:%line\\)) - %msg%throwable%n"
  level:
    root: WARN
    com.zaxxer.hikari: DEBUG
    org.springframework.jdbc.datasource: DEBUG
  org:
    hibernate:
      dialect: INFO
    springframework:
      boot:
        test:
          context:
            SpringBootTestContextBootstrapper: WARN
      test:
        context:
          support:
            AbstractContextLoader: OFF
            AnnotationConfigContextLoaderUtils: OFF
    zaxxer:
      hikari:
        HikariDataSource: INFO